name: run-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
#      - run: pip install -r requirements.txt
      - run: python3 test_main.py
